name: Use Secrets

on: [push]
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Use secret

        run: |

          echo "Username is ${{ secrets.secret1 }}"

          echo "Password length is ${#secret1}"

        env:

          SECRETFILE: ${{ secrets.secret1 }}
 
