name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Composite Action
        uses: ./.github/actions/java-build
        with:
          java-version: "17"
